name: ffr-dam impact
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  # Core scientific python
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - math
  - fiona
  - geopandas
  - rasterio
  - zipfile
  - earthpy
  - urlib.request
  - warning
 

  # Natural language processing
  - nltk
  - textblob

  # Jupyter Environment
  - papermill
  - autopep8
  - notebook
  - ipython
